function files = exportReport(data, results, outdir, figureFiles)
%EXPORTREPORT Export numeric tables, manuscript tables and a browsable report.
arguments
    data (1,1) struct
    results (1,1) struct
    outdir (1,1) string
    figureFiles (:,1) string = strings(0,1)
end
tableDir=fullfile(outdir,'Tables'); if ~isfolder(tableDir), mkdir(tableDir); end
files=struct('report',fullfile(outdir,'Report.html'),'workbook',fullfile(outdir,'Analysis_Tables.xlsx'), ...
    'patient_csv',fullfile(outdir,'paired_plan_patient_data.csv'), ...
    'json',fullfile(outdir,'analysis_results.json'),'mat',fullfile(outdir,'analysis_results.mat'), ...
    'methods',fullfile(outdir,'Methods.txt'),'figures',figureFiles);
names=string(fieldnames(results.tables)); csvs=strings(numel(names),1);
for i=1:numel(names)
    t=results.tables.(names(i)); csvs(i)=fullfile(tableDir,names(i)+'.csv');
    writetable(t,csvs(i));
    writetable(t,files.workbook,'Sheet',names(i),'UseExcel',false,'WriteMode','overwritesheet');
end
writetable(data.patientTable,files.patient_csv);
writetable(data.patientTable,files.workbook,'Sheet','Patient_Data','UseExcel',false,'WriteMode','overwritesheet');
methods=[ ...
    "Analysis Data of glottic cancer"; ...
    "Source: "+string(results.analysis.source_file)+"; worksheet SO LIEU."; ...
    "Pairs: "+string(results.analysis.n_paired_patients)+". All patient IDs in outputs are anonymous."; ...
    "3DCRT/PBC and IMRT/AAA are paired whole planning workflows."; ...
    "Source label 3DCRT/PCB is interpreted as PBC, following the supplied planning report."; ...
    "Raw selected cells are validated and derived endpoints are recomputed on each import."; ...
    "Worse-side mean = max(left Dmean, right Dmean) in each plan; peak = max(left Dmax, right Dmax) independently."; ...
    "Arithmetic bilateral mean = (left Dmean + right Dmean)/2; no volume weighting."; ...
    "All deltas = IMRT minus 3DCRT. Scatterplot reduction = 3DCRT minus IMRT."; ...
    "V66 values in the current Excel layout are already percent; V66 differences are percentage points."; ...
    "Sample SD uses n-1. Quartiles use linear interpolation h=1+(n-1)*p, matching NumPy."; ...
    "Mean-difference 95% CI uses Student t with n-1 degrees of freedom; tests are two-sided."; ...
    "Wilcoxon uses exact random-sign probabilities on twice the midranks; differences rounded to 8 decimals only for ranking; zeros omitted."; ...
    "Binary proportions use exact Clopper-Pearson 95% CI. McNemar is the exact symmetric binomial test on discordant pairs."; ...
    "Holm adjustment: all 15 secondary continuous paired-t tests excluding worse-side Dmean; all 10 binary tests including composite checks."; ...
    "Primary paired-t p is unadjusted. All confidence intervals are nominal, unadjusted 95% intervals."; ...
    "Spearman uses midranks with the t approximation; Pearson intervals use Fisher z. Correlation p values are unadjusted."; ...
    "Carotid cutoffs: Dmean <20 Gy and peak Dmax <=50 Gy. Target checks: D95 >=66 Gy; D99.9 >=62.7 Gy; Dmax <=72.6 Gy."; ...
    "Table3 omits V66 and the mean-plus-target-only criterion from the 10-test family; full family is in TableS3."; ...
    "Patient relative reduction = 100*(3DCRT-IMRT)/3DCRT; zero baselines are undefined and excluded from this descriptor only."; ...
    "Bootstrap: "+string(results.bootstrap.n_resamples)+" paired resamples; seed "+string(results.bootstrap.seed)+"; MATLAB mt19937ar."; ...
    "MATLAB bootstrap draws differ from reference NumPy PCG64 draws; deterministic analytic results reproduce the reference."; ...
    "Empty conditional denominators and undefined correlations appear as NaN/null or --, with status in JSON."; ...
    "Exploratory analysis only: no clinical outcomes or injury thresholds are estimated."; ...
    string(results.data_concerns(:)); ...
    "MATLAB: "+string(results.analysis.matlab_version)+"; tool version: "+string(results.analysis.code_version)];
writeText(files.methods,strjoin(methods,newline));
results.outputFiles=files;
j=results;
for i=1:numel(names), j.tables.(names(i))=table2struct(results.tables.(names(i))); end
writeText(files.json,string(jsonencode(j,'PrettyPrint',true,'ConvertInfAndNaN',true)));
save(files.mat,'data','results');
writeText(files.report,htmlReport(results,methods,figureFiles));
files.table_csv=csvs;
allFiles=[files.report;files.workbook;files.patient_csv;files.json;files.mat;files.methods;csvs;figureFiles];
manifest=struct('completed',true,'code_version',results.analysis.code_version, ...
    'n_paired_patients',results.analysis.n_paired_patients,'files',allFiles);
writeText(fullfile(outdir,'Manifest.json'),string(jsonencode(manifest,'PrettyPrint',true)));
end

function writeText(path,value)
[fid,msg]=fopen(path,'w','n','UTF-8');
if fid<0, error('glottic:WriteFailed','Cannot write %s: %s',path,msg); end
guard=onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',value);
end

function html=htmlReport(r,methods,figureFiles)
m=r.metrics.carotid_worse_Dmean_Gy;
html="<!doctype html><html lang='en'><head><meta charset='utf-8'>"+ ...
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"+ ...
    "<title>Analysis Data of glottic cancer</title><style>"+ ...
    "body{font:16px Arial,sans-serif;color:#222;background:#f4f7fa;margin:0}"+ ...
    "main{max-width:1400px;margin:auto;padding:32px}h1{font-size:30px}h2{margin-top:36px}"+ ...
    "section,.summary{background:white;border:1px solid #dce3ea;border-radius:8px;padding:20px;margin:20px 0}"+ ...
    "a{color:#0072b2}.scroll{overflow:auto}table{border-collapse:collapse;font-size:14px;width:100%}"+ ...
    "th,td{text-align:left;padding:10px;border-bottom:1px solid #ddd;white-space:nowrap}"+ ...
    "th{background:#e9f0f6}tr:nth-child(even){background:#f7f9fb}img{width:100%;height:auto}"+ ...
    ".note{color:#475569;line-height:1.6}nav{line-height:1.8}pre{white-space:pre-wrap;font:14px Arial;line-height:1.6}"+ ...
    "@media print{body{background:white}main{padding:0}section{break-inside:avoid;border:0}.scroll{overflow:visible}th,td{white-space:normal}}</style></head><body><main>";
html=html+"<h1>Analysis Data of glottic cancer</h1><p>Paired 3DCRT/PBC and IMRT/AAA planning data. "+string(r.analysis.n_paired_patients)+" anonymous patient pairs.</p>";
html=html+"<div class='summary'><strong>Worse-side carotid mean dose</strong><p>3DCRT: "+ ...
    string(sprintf('%.2f +/- %.2f Gy',m.CRT.mean,m.CRT.sd))+". IMRT: "+ ...
    string(sprintf('%.2f +/- %.2f Gy',m.IMRT.mean,m.IMRT.sd))+".</p><p>Mean paired difference (IMRT minus 3DCRT): "+ ...
    string(sprintf('%.2f Gy; 95%% CI %.2f to %.2f Gy.',m.delta.mean,m.delta_mean_95CI))+ ...
    "</p><p class='note'>All analyses are exploratory. Carotid cutoffs are operational planning descriptors.</p></div>";
html=html+"<nav><a href='Analysis_Tables.xlsx'>Excel tables</a> &middot; <a href='paired_plan_patient_data.csv'>Anonymous paired data</a> &middot; "+ ...
    "<a href='analysis_results.json'>Full numeric results</a> &middot; <a href='Methods.txt'>Methods and definitions</a></nav>";
mainNames=["Table1" "Table2" "Table3" "TableS1" "TableS2" "TableS3" "TableS4" "TableS5" "TableS6" "Sensitivity" "Descriptive"];
titles=["Table 1. Carotid and thyroid dosimetry" "Table 2. Target dosimetry" ...
    "Table 3. Planning markers and paired transitions" "Table S1. All continuous endpoints" ...
    "Table S2. IMRT joint mean and peak threshold counts" "Table S3. All binary criteria and paired transitions" ...
    "Table S4. Binary proportions and exact confidence intervals" "Table S5. Joint carotid mean and peak categories" ...
    "Table S6. Exploratory carotid reduction versus target change correlations" ...
    "Descriptive carotid mean threshold sensitivity" "Additional descriptive proportions"];
for i=1:numel(mainNames)
    name=mainNames(i); t=r.tables.(name);
    html=html+"<section><h2>"+titles(i)+"</h2><p><a href='Tables/"+name+".csv'>Download CSV</a></p>"+tableHTML(t)+"</section>";
end
html=html+"<p class='note'>CRT columns mean 3DCRT/PBC. Delta units are Gy, except V66 in percentage points. -- denotes the unadjusted primary endpoint in a Holm column or an undefined result. Lost = 3DCRT attained and IMRT did not; gained = IMRT attained and 3DCRT did not. All proportions use the displayed denominator.</p>";
figureTitles=["Left and right carotid mean doses";"Carotid mean and peak doses with marker attainment"; ...
    "Target coverage and maximum dose";"Patient planning marker matrix";"Exploratory correlations"];
figureNames=["Fig1";"Fig2";"Fig3";"Fig4";"FigS1"];
for i=1:5
    if any(endsWith(figureFiles,figureNames(i)+'.png'))
        html=html+"<section><h2>"+figureNames(i)+". "+figureTitles(i)+"</h2><img src='Figures/"+figureNames(i)+ ...
            ".png' alt='"+figureTitles(i)+"'><p><a href='Figures/"+figureNames(i)+".pdf'>Vector PDF</a> &middot; "+ ...
            "<a href='Figures/"+figureNames(i)+".tiff'>TIFF</a> &middot; <a href='Figures/"+figureNames(i)+".fig'>Editable MATLAB figure</a></p></section>";
    end
end
html=html+"<section><h2>Methods and interpretation</h2><pre>"+escapeHTML(strjoin(methods,newline))+"</pre></section></main></body></html>";
end

function s=tableHTML(t)
s="<div class='scroll'><table><thead><tr>";
for name=string(t.Properties.VariableNames), s=s+"<th>"+escapeHTML(replace(name,'_',' '))+"</th>"; end
s=s+"</tr></thead><tbody>";
for i=1:height(t)
    s=s+"<tr>";
    for j=1:width(t)
        value=t{i,j}; if iscell(value), value=value{1}; end
        if isnumeric(value)
            if isnan(value), value="--";
            elseif contains(lower(t.Properties.VariableNames{j}),'p') && ...
                    (endsWith(t.Properties.VariableNames{j},'_P'))
                value=string(sprintf('%.4g',value));
            else, value=string(sprintf('%.4g',value)); end
        end
        s=s+"<td>"+escapeHTML(string(value))+"</td>";
    end
    s=s+"</tr>";
end
s=s+"</tbody></table></div>";
end

function s=escapeHTML(s)
s=replace(string(s),'&','&amp;'); s=replace(s,'<','&lt;'); s=replace(s,'>','&gt;');
s=replace(s,'"','&quot;'); s=replace(s,"'",'&#39;');
end
